services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: tim
      POSTGRES_DB: auth_db
      PGDATA: /var/lib/postgresql/data/inf
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/data/postgres/inf
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres_network
    volumes:
      - pgadmin:/var/lib/pgadmin/inf
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin:

networks:
  postgres_network:
    driver: bridge