server.port=8085

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=tim
spring.datasource.password=tim
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# gRPC client to image-storage-service
grpc.client.image-storage-service.address=static://image-storage-service:9094
grpc.client.image-storage-service.negotiation-type=plaintext

jwt.secret=secret_key
jwt.secret=secret_key


